#!/system/bin/sh

useragent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0"
initdir="/sdcard/initrom"
download(){
# $1 = url
# $2 = local path
# lets see that curl exits successfully
until /system/bin/curl -s -k -L -A "$useragent" -o "$2" "$1" ;do
  sleep 25
done
}

if [ -f $initdir/init_done ]; then
  #Create logfile
  if [ ! -e /sdcard/vm.log ] ;then
    touch /sdcard/vm.log
  fi

  initfile="/system/etc/init.d/49vmapper"

  if ! [[ -f "$initfile" ]] ;then
    #Handle custom rom with vmapper config file
    customConfig="/system/etc/vm_custom_config"
    if [[ -f "$customConfig" ]] ;then
      cp "$customConfig" "/data/local/vm_custom_config"
      echo "`date +%Y-%m-%d_%T` First boot: found custom rom vmapper config file - copied to /data/local/vm_custom_config" >> /sdcard/vm.log
    fi

    echo "`date +%Y-%m-%d_%T` First boot: 49vmapper does not exist yet" >> /sdcard/vm.log
    mount -o remount,rw /
    sleep 20

    CustomRom="$(find /mnt/media_rw/ -iname CustomRom.txt 2>/dev/null)"
    CustomUrl="$(awk 'NR==1{print $1}' "$CustomRom")"
    initfirst="/system/etc/init.d/49vmapper_first"
    if [[ "$CustomUrl" ]] ;then
      download "$CustomUrl" "$initfile"
      chmod +x "$initfile"
      mount -o remount,ro /
      echo "`date +%Y-%m-%d_%T` First boot: downloaded 49vmapper from $CustomUrl" >> /sdcard/vm.log
    elif [[ -f "$initfirst" ]] ;then
      mv "$initfirst" "$initfile"
      chmod +x "$initfile"
      mount -o remount,ro /
      echo "`date +%Y-%m-%d_%T` First boot: 49vmapper from Custom Rom" >> /sdcard/vm.log
    else
      download https://raw.githubusercontent.com/v-mapper/vmconf/main9/scrips/49vmapper "$initfile"
      chmod +x "$initfile"
      mount -o remount,ro /
      echo "`date +%Y-%m-%d_%T` First boot: downloaded 49vmapper from vmconf main" >> /sdcard/vm.log
    fi

    echo "`date +%Y-%m-%d_%T` First boot: starting 49vmapper for the first time" >> /sdcard/vm.log
    /system/bin/sh -x "$initfile"
  fi
fi
