#!/system/bin/sh

useragent="Mozilla/5.0 (Windows; U; Windows NT 5.1; de; rv:1.9.2.3) Gecko/20100401 Firefox/3.6.3"
download(){
# $1 = url
# $2 = local path
# lets see that curl exits successfully
until /system/bin/curl -s -k -L -A "$useragent" -o "$2" "$1" ;do
 sleep 25
done
}

if [[ -f /data/local/madromlogs/42mad.log ]] ;then
  rm -f -- /data/local/madromlogs/*.log.old
  for f in /data/local/madromlogs/*.log; do 
    mv -- "$f" "${f%.log}.log.old"
  done
fi

initfile="/system/etc/init.d/42mad"

if ! [[ -f "$initfile" ]] ;then
 mkdir -p /data/local/madromlogs/
 mount -o remount,rw /system
 sleep 30
 CustomRom="$(find /mnt/media_rw/ -iname CustomRom.txt 2>/dev/null)"
 CustomUrl="$(awk 'NR==1{print $1}' "$CustomRom")"
 sleep 5
 if [[ "$CustomUrl" ]] ;then
  download "$CustomUrl" "$initfile" && chmod +x /system/etc/init.d/*
  echo "Installing 42mad from custom url"
 else
  download https://raw.githubusercontent.com/v-mapper/vmconf/main/42mad "$initfile" && chmod +x /system/etc/init.d/*
  echo "Installing 42mad from vmconf main branch"
 fi
 sleep 5
 /system/bin/sh -x "$initfile" 2>"/data/local/madromlogs/42mad.log"
fi
