#!/system/bin/sh
# version 0.5

#Create logfile
if [ ! -e /sdcard/vm.log ] ;then
    touch /sdcard/vm.log
fi

#update vmapper.sh and 55vmapper
old55=$(head -5 /system/etc/init.d/55vmapper | grep '# version' | awk '{ print $NF }')
oldsh=$(grep '# version' /system/bin/vmapper.sh | awk '{ print $NF }')

mount -o remount,rw /system
/system/bin/curl -s -k -L -o /system/bin/vmapper.sh https://raw.githubusercontent.com/dkmur/vmconf/main/vmapper.sh
chmod +x /system/bin/vmapper.sh
/system/bin/curl -s -k -L -o /system/etc/init.d/55vmapper https://raw.githubusercontent.com/dkmur/vmconf/main/55vmapper
chmod +x /system/etc/init.d/55vmapper
mount -o remount,ro /system

new55=$(head -5 /system/etc/init.d/55vmapper | grep '# version' | awk '{ print $NF }')
newsh=$(grep '# version' /system/bin/vmapper.sh | awk '{ print $NF }')
echo "`date +%Y-%m-%d_%T` Device rebooted, 55vmapper $old55=>$new55, vmapper.sh $oldsh=>$newsh" >> /sdcard/vm.log

# have vmapper.sh check for updated vmapper version in wizzard
! [[ -f /sdcard/disableautovmapperupdate ]] && sh -x /system/bin/vmapper.sh -uvw
