#!/system/bin/sh
# version="0.2"

#update vmapper.sh and 55vmapper
mount -o remount,rw /system
/system/bin/curl -L -o /system/bin/vmapper.sh -k -s https://raw.githubusercontent.com/dkmur/vmconf/main/vmapper.sh
chmod +x /system/bin/vmapper.sh
/system/bin/curl -L -o /system/etc/init.d/55vmapper -k -s https://raw.githubusercontent.com/dkmur/vmconf/main/55vmapper
chmod +x /system/etc/init.d/55vmapper
mount -o remount,ro /system

# have vmapper.sh check for updated vmapper version in wizzard
! [[ -f /sdcard/disableautovmapperupdate ]] && sh -x /system/bin/vmapper.sh -uvw
