#!/system/bin/sh
# version 1.3.9

logfile="/sdcard/vm.log"
vmconf="/data/data/de.vahrmap.vmapper/shared_prefs/config.xml"
vmhistory="/sdcard/VMHistory.log"
RUN_EVERY=60
REBOOT_AFTER=3
MAX_DAILY_REBOOT=10

#Create logfile if it doesn't exist yet
if [ ! -e $logfile ] ;then
  touch $logfile
fi

# stderr to logfile
exec 2>> $logfile

#Check if vmapper watchdog script is disabled
if [ -f /sdcard/disable_vm_watchdog ] ;then
  echo "`date +%Y-%m-%d_%T` VMwatchdog: disabled" >> $logfile
  exit
fi

#Check if vmapper is installed
if [ ! -f $vmconf ] ;then
  echo "`date +%Y-%m-%d_%T` VMwatchdog: not started, no vmapper install found" >> $logfile
  exit
fi

#Lets start by sleeping a bit
sleep 300

check_vm() {
vm_running=$(ps | grep de.vahrmap.vmapper | awk -F. '{ print $NF }')
}

check_playstore() {
playstore=$(ps | grep com.android.vending | awk -F. '{ print $NF }')
}


echo "`date +%Y-%m-%d_%T` VMwatchdog Started" >> $logfile

i=0

while true; do

   #cleanup History File
   history_size=$(wc -l < $vmhistory)
   if [ -f $vmhistory ] && [ $history_size -gt 10000 ] ;then
     echo "`date +%Y-%m-%d_%T` VMwatchdog: Cleaning History File" >> $logfile
     tail -n1000 $vmhistory > $vmhistory
     exit
   fi

   #Stop Monitoring during the night
   if [[ "$currenttime" > "00:00" ]] && [[ "$currenttime" < "6:30" ]]; then
	  active_monitor=0
   else
	  active_monitor=1
   fi

   #Get History Last Update
   if [ -f $vmhistory ] ;then
     current_epoch=$(date +%s)
     history_epoch=$(stat -c '%Y' $vmhistory)
     history_diff=$(expr $current_epoch - $history_epoch)
   fi

   #Get Last lines from History
   history_line_1=$(tail -n1 $vmhistory | cut -d";" -f2-4)
   history_line_2=$(tail -n4 $vmhistory | cut -d";" -f2-4 | head -n1)

  check_vm
  check_playstore

  #Check that Internet is alive
  until ping -c1 8.8.8.8 >/dev/null 2>/dev/null
  do
    echo "`date +%Y-%m-%d_%T` VMwatchdog: Internet Connection lost, sleeping for 5 minutes"  >> $logfile
    sleep 300
  done

  if (( $i > $REBOOT_AFTER )) ;then
    if [ $(cat $logfile | grep `date +%Y-%m-%d` | grep VMwatchdog | grep rebooting | wc -l) -gt $MAX_DAILY_REBOOT ] ;then
      echo "`date +%Y-%m-%d_%T` VMwatchdog: I've already rebooted $MAX_DAILY_REBOOT times today, too tired now, see you tomorrow..."  >> $logfile
      sleep $(( 86400 - $(( $(date '+%-H *3600 + %-M *60 + %-S') )) ))
    else
      echo "`date +%Y-%m-%d_%T` VMwatchdog: vmapper not running, tried to restart vmapper $REBOOT_AFTER times, rebooting device"  >> $logfile
      reboot
    fi

  elif [ -z "$playstore" ] ;then
    echo "`date +%Y-%m-%d_%T` VMwatchdog: Playstore disabled, enabling" >> $logfile
    pm enable com.android.vending

  elif [ -z "$vm_running" ] ;then
    echo "`date +%Y-%m-%d_%T` VMwatchdog: vmapper not running, restarting" >> $logfile 
    am broadcast -n de.vahrmap.vmapper/.RestartService --ez autostart true
    i=$((i+1))
    sleep 5
    check_vm
    if [ -z "$vm_running" ] ;then
      echo "`date +%Y-%m-%d_%T` VMwatchdog: vmapper not running after restart attempt $i, waiting for next loop to retry" >> $logfile
    else
      echo "`date +%Y-%m-%d_%T` VMwatchdog: vmapper running after restart attempt $i" >> $logfile
      i=0
    fi

  elif [ -f $vmhistory ] && [ $history_diff -gt 300 ] && [ $active_monitor == 1 ] ;then
    echo "`date +%Y-%m-%d_%T` VMwatchdog: History not updated for 5 minutes, restarting service" >> $logfile
    am broadcast -n de.vahrmap.vmapper/.RestartService --ez autostart true
    i=$((i+1))
    sleep 5

  elif [ -f $vmhistory ] && [ "$history_line_1" == "$history_line_2" ] ;then
    echo "`date +%Y-%m-%d_%T` VMwatchdog: No change in history for 2 mins, restarting service" >> $logfile
    am broadcast -n de.vahrmap.vmapper/.RestartService --ez autostart true
    i=$((i+1))
    sleep 5

  fi


  sleep $RUN_EVERY

done
