CREATE TABLE IF NOT EXISTS `ATVsummary` (
  `timestamp` datetime NOT NULL,
  `deviceName` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `arch` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `productmodel` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `android_version` varchar(6) DEFAULT NULL,
  `vmapperSh` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vmapper49` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vmwatchdog56` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `whversion` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pogo` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vmapper` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pogoupdate` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vmupdate` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `playstoreenabled` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `playstore` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `proxyinfo` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `whenabled` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `temperature` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `magisk` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `magisk_modules` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `macw` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mace` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ip` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ext_ip` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hostname` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `diskSysPct` int(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `diskDataPct` int(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bootdelay` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `gzip` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `betamode` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `selinux` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `daemon` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `authpassword` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `authuser` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `authid` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `postdest` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fridastarted` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `patchedpid` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `openlucky` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rebootminutes` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `deviceid` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `websocketurl` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `catchPokemon` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `catchRare` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `launcherver` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rawpostdest` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lat` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lon` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `overlay` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `numPogo` int(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vmc_reboot` int(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`deviceName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS `ATVstats` (
  `timestamp` timestamp NOT NULL,
  `RPL` smallint(6) NOT NULL,
  `deviceName` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `temperature` int(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `memTot` int(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `memFree` int(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `memAv` int(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `memPogo` int(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `memVM` int(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cpuSys` int(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cpuUser` int(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cpuL5` float COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cpuL10` float COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cpuLavg` float COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cpuPogoPct` float COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cpuVmPct` float COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `diskSysPct` int(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `diskDataPct` int(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
PRIMARY KEY (`deviceName`,`timestamp`,`RPL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ATVlogs` (
  `timestamp` datetime NOT NULL,
  `deviceName` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `vmc_reboot` int(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vm_patcher_restart` int(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vm_pogo_restart` int(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vm_injection` int(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vm_injectTimeout` int(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vm_crash_dialog` int(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vm_consent` int(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vm_ws_stop_pogo` int(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vm_ws_start_pogo` int(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vm_authStart` int(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vm_authSuccess` int(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vm_authFailed` int(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vm_Gtoken` int(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vm_Ptoken` int(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vm_PtokenMaster` int(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vm_died` int(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
PRIMARY KEY (`deviceName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `version` (
  `key` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `version` smallint(6) NOT NULL,
  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- update version
INSERT IGNORE INTO version values ('vmapper_atvdetails',1);
UPDATE version set version = 5 where version.key = 'vmapper_atvdetails';
