{
 "title": "VM ATV Details overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "ATV general",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\nifnull(arch,'no_data') as 'Architecture',\nifnull(productmodel,'nodata') as 'Productmodel',\nifnull(pogoupdate, 'no_data') as 'Pogo Update',\nifnull(vmupdate, 'no_data') as 'VM Update',\nifnull(playstoreenabled, 'no_data') as 'Playstore Update',\nifnull(whenabled, 'no_data') as 'WH enabled',\nifnull(proxyinfo, 'no_data') as 'Proxy',\n\ncount(deviceName) as '#devices'\nfrom ATVsummary\nwhere timestamp > now() - interval 1 day\nGROUP BY arch,productmodel,vmapperSh,vmapper49,whversion\n"
    }
   ]
  },
  {
   "title": "Magisk / modules",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\nifnull(magisk,'no_data') as 'Magisk',\nifnull(magisk_modules,'no_data') as 'Modules loaded',\nifnull(pifversion,'no_data') as 'PIF Ver.',\ncount(deviceName) as '#devices'\nfrom ATVsummary\nwhere timestamp > now() - interval 1 day\nGROUP BY magisk, magisk_modules\n"
    }
   ]
  },
  {
   "title": "Versions",
   "type": "table",
   "gridPos": { "h": 4, "w": 17, "x": 7, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\nifnull(pogo,'no_data') as 'PoGo',\nifnull(vmapper,'no_data') as 'Vmapper',\nifnull(vmapperSh,'no_data') as 'vmapper.sh',\nifnull(vmapper49,'no_data') as 'vmapper49',\nifnull(vmwatchdog56,'no_data') as 'vmwatchdog56',\nifnull(whversion,'no_data') as 'wh_sender',\nifnull(playstore,'no_data') as 'playstore Ver',\ncount(deviceName) as '#devices'\nfrom ATVsummary\nwhere timestamp > now() - interval 1 day\nGROUP BY pogo,vmapper\n"
    }
   ]
  },
  {
   "title": "Vmapper settings",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\nifnull(rawpostdest, 'no_data') as 'rdmUrl',\nifnull(authuser, 'no_data') as 'authUser',\nifnull(authpassword, 'no_data') as 'authPassword',\nifnull(websocketurl, 'no_data') as 'websocketUrl',\nifnull(rebootminutes, 'no_data') as 'rebootMin',\nifnull(bootdelay, 'no_data') as 'bootDelay',\nifnull(betamode, 'no_data') as 'Betamode',\nifnull(daemon, 'no_data') as 'Daemon',\nifnull(openlucky, 'no_data') as 'OpenLucky',\nifnull(catchPokemon, 'no_data') as 'catchMons',\nifnull(catchRare, 'no_data') as 'catchRare',\ncount(deviceName) as '#devices'\nfrom ATVsummary\nwhere timestamp > now() - interval 1 day\nGROUP BY rawpostdest,authUser,authPassword,websocketUrl,rebootMinutes,bootDelay,Betamode,Daemon,OpenLucky,catchPokemon,catchRare"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\nmin(temperature) as 'minTemp',\navg(temperature) as 'avgTemp',\nmax(temperature) as 'maxTemp'\nfrom ATVsummary\nwhere timestamp > now() - interval 1 day"
    }
   ]
  },
  {
   "title": "Temperature (Top 5)",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\ndeviceName,\nTemperature\nfrom ATVsummary\nwhere timestamp > now() - interval 1 day\norder by temperature DESC\nlimit 5\n"
    }
   ]
  },
  {
   "title": "Temperature (Lowest 5)",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\ndeviceName,\nTemperature\nfrom ATVsummary\nwhere timestamp > now() - interval 1 day\norder by temperature ASC\nlimit 5\n"
    }
   ]
  }
 ]
}